# ============================================
# SmartMarket - Configuracao Padrao
# ============================================
spring.profiles.active=dev

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
