# ============================================
# SmartMarket - Configuracao Padrao
# ============================================
spring.profiles.active=dev

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# JWT
jwt.secret=AuGDB2cOybnJOZ6CzfSQigrjx6Xpf1OcSSTWd8UPo0UrpMkMa7BKrQ4G50Iy8cwC
jwt.expiration=86400000
